#!/bin/bash

echo "🔑 Creating New Google AI API Key Guide"
echo "======================================="
echo ""
echo "🚀 IMMEDIATE SOLUTION: Get a new API key"
echo ""
echo "📋 Steps:"
echo "1. Open: https://aistudio.google.com/app/apikey"
echo "2. Sign in with a different Google account (if needed)"
echo "3. Click 'Create API Key'"
echo "4. Copy the new API key"
echo "5. Update your environment variables"
echo ""
echo "🔧 Update Environment Variables:"
echo "   Local (.env.local):"
echo "   GOOGLE_API_KEY=your_new_api_key_here"
echo ""
echo "   Vercel (Production):"
echo "   vercel env rm GOOGLE_API_KEY"
echo "   vercel env add GOOGLE_API_KEY"
echo "   [Enter your new API key]"
echo "   vercel --prod"
echo ""
echo "⚡ Or use different account API key from your 'other account'"