#!/bin/bash

echo "🚀 Google AI Quota Upgrade Guide"
echo "=================================="
echo ""
echo "📊 Current Issue: 429 Too Many Requests - Quota Exceeded"
echo "🔑 API Key: AIzaSyBBL3roRt5nqsiXDMzd8zXTpB9TB_7jdGQ"
echo ""
echo "💡 SOLUTION: Upgrade your Google AI quota"
echo ""
echo "📋 Steps to Increase Quota:"
echo "1. Visit: https://ai.google.dev/pricing"
echo "2. Go to: https://aistudio.google.com/app/quota"
echo "3. Click on 'Increase Quota' or 'Upgrade Plan'"
echo "4. Choose a paid plan with higher limits:"
echo "   • Pay-as-you-go: $0.075 per 1K characters"
echo "   • Higher rate limits: 1000+ requests/min"
echo ""
echo "📈 Quota Options:"
echo "   • Free: 15 req/min, 1,500 req/day"
echo "   • Paid: 1000+ req/min, unlimited daily"
echo ""
echo "🔍 Monitor Usage:"
echo "   • Visit: https://ai.dev/usage"
echo "   • Check current quota consumption"
echo ""
echo "💰 Cost Estimate for AI-TeleSuite:"
echo "   • ~$0.10-0.50 per call scoring request"
echo "   • Monthly cost: $10-50 for moderate usage"
echo ""
echo "⚡ Quick Fix Alternative:"
echo "   • Wait 24 hours for quota reset"
echo "   • Use a different Google account/API key"